.test:
  cache:
    paths:
    - node_modules
  coverage: '/^Statements *: (\d+\.\d+%)/'
  script:
  - npm install
  - npm test

test:node8:
  extends: .test
  cache:
    key: node8
  image: node:8-alpine

test:node4:
  extends: .test
  cache:
    key: node4
  image: node:4.5
